title    Alter Linux install medium (%ARCH%, UEFI)
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-%ALTERISO_KERNEL_NAME%
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-%ALTERISO_KERNEL_NAME%.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID%
