title    %ALTERISO_OS_NAME% install medium (%ARCH%, UEFI) with speech
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-%ALTERISO_KERNEL_NAME%
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-%ALTERISO_KERNEL_NAME%.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% accessibility=on
