services:
  alteriso:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ALTERISO_VERSION
        - GIT_REVISION
    privileged: true
    working_dir: /app
    volumes:
      - ./out:/app/out
      # - ./work:/app/work
    command:
      - /bin/bash
      - -lc
      - |
        alteriso clean
        alteriso profile build /usr/share/alteriso/configs/xfce
