services:
  alteriso:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_REVISION
    privileged: true
    working_dir: /app
    volumes:
      - ./out:/app/out
      # - ./work:/app/work
    command: alteriso profile build /usr/share/alteriso/configs/xfce

