language: shell
sudo: required
addons:
  apt:
    packages:
      - ninja
      - cmake
      - clang
      - qtbase5-dev
script:
  - bash -c 'shopt -s globstar nullglob; shellcheck -s bash --exclude=SC2068 -S error **/*.{sh,ksh,bash}'
  - bash -c 'shopt -s globstar nullglob; shellcheck -s bash --exclude=SC2068 -S error tools/*.{sh,ksh,bash}'
git:
  submodules: false
  language: bash
