#!/usr/bin/env bash

# Alter Linux build config
# The variables here will override the default values.
# This configuration file follows the bash syntax.

iso_name=alterlinux
iso_label="ALTER_$(date +%Y%m)"
iso_publisher="Alter Linux <http://www.archlinux.org>"
iso_application="Alter Linux Live/Rescue CD"
iso_version=$(date +%Y.%m.%d)
install_dir=alter
work_dir=work
out_dir=out
gpg_key=

# AlterLinux settings
password=alter

# Set to true to enable plymouth.(-b)
boot_splash=false

# Set to true to build using the lts kernel.(-l)
lts_kernel=false

# Set the theme name of plymouth.
theme_name="alter-logo"

# Set the package name of the plymouth theme.
# Install only if plymouth is enabled.
# If it is not packaged, leave this item empty and place those files in airootfs.
theme_pkg="plymouth-theme-alter-logo-git"

# See the `mksquashfs` help for details on these items.
sfs_comp="zstd"
sfs_comp_opt=""