#!/usr/bin/env bash
# 
# Yamada Hayao 
# Twitter: @Hayao0819
# Email  : hayao@fascode.net
#
# (c) 2019-2020 Fascode Network.
#
# Alter Linux build config
# The variables here will override the default values.
# This configuration file follows the bash syntax.

# OS name used for the name of the image file.
iso_name=alterlinux

# Image file label
iso_label="ALTER_$(date +%Y%m)"

# Image file creator information
iso_publisher="Alter Linux <http://www.archlinux.org>"

# Image file name (not file name)
iso_application="Alter Linux Live/Rescue CD"

# Image file version
iso_version=$(date +%Y.%m.%d)

# Directory name used for installation
install_dir=alter

# Work directory to execute pacstrap etc
work_dir=work

# Directory to output image file and checksum
out_dir=out

# Key used for signature
gpg_key=

# AlterLinux settings
password=alter

# Set to true to enable plymouth.(-b)
boot_splash=false

# Set the theme name of plymouth.
theme_name="alter-logo"

# Set the package name of the plymouth theme.
# Install only if plymouth is enabled.
# If it is not packaged, leave this item empty and place those files in airootfs.
theme_pkg="plymouth-theme-alter-logo-git"

# See the `mksquashfs` help for details on these items.
sfs_comp="zstd"
sfs_comp_opt=""

# Set the kernel that live session use.
# Please don't set anything if you want to use normal kernel.
# As of February 23, 2020, the available kernels are lts, zen, ck, , rt and lqx.
kernel=

# Set debug mode.
# This setting can only be set to true or false.
# When enabled, bash debug mode is enabled, making it easier to identify which command caused the error.
debug=false