#!/usr/bin/env bash
#
# Yamada Hayao
# Twitter: @Hayao0819
# Email  : hayao@fascode.net
#
# (c) 2019-2020 Fascode Network.
#
# config
#
# Overwrites the first to read and set the build script
# This configuration file follows the bash syntax.
#

# OS name used for startup screen, etc.
os_name="Alter Linux"

# OS name used for the name of the image file.
iso_name=alterlinux

# Image file label
iso_label="ALTER_$(date +%Y%m%d)"

# Image file creator information
iso_publisher='Fascode Network <https://fascode.net>'

# Image file name (not file name)
iso_application="${os_name} Live/Rescue CD"

# Image file version
iso_version=$(date +%Y.%m.%d)

# Directory name used for installation
install_dir=alter

# Work directory to execute pacstrap etc
work_dir=work

# Directory to output image file and checksum
out_dir=out

# Key used for signature
gpg_key=

# AlterLinux settings
password=alter

# Set to true to enable plymouth.(-b)
boot_splash=false

# Set the theme name of plymouth.
theme_name="alter-logo"

# Set the package name of the plymouth theme.
# Install only if plymouth is enabled.
# If it is not packaged, leave this item empty and place those files in airootfs.
theme_pkg="plymouth-theme-alter-logo-git"

# See the `mksquashfs` help for details on these items.
sfs_comp="zstd"
sfs_comp_opt=""

# Set the kernel that live session use.
# Please don't set anything if you want to use normal kernel.
# As of February 23, 2020, the available kernels are lts, zen, ck, , rt and lqx.
kernel=zen

# Set debug mode.
# This setting can only be set to true or false.
# When enabled, bash debug mode is enabled, making it easier to identify which command caused the error.
debug=false

# Set the Japanese mode.
# When this is enabled, the packages in the japanese package list will be installed.
# A file for Japanese input is added.
japanese=false

# Enable post-build cleaning.
# When enabled, airootfs in the working directory is deleted after squashfs is created.
cleaning=false

# Set the user's default shell.
usershell="/bin/bash"


# Set whether to check the build.
# If true, do not check. If false, confirm.
noconfirm=false
