#!/bin/bash

build() {
    MODULES="nfs"
    SCRIPT="archiso_pxe_nfs"

    add_binary /usr/lib/initcpio/nfsmount /bin/nfsmount
}

help() {
    cat <<HELPEOF
  This hook loads the necessary modules for boot via PXE and NFS.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
