#!/bin/bash

build() {
    SCRIPT="archiso_pxe_http"

    add_binary curl
}

help() {
cat<<HELPEOF
  This hook loads the necessary modules for boot via PXE and HTTP.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
