#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
    start)
        stat_busy "Starting XFCE4"
        su -l arch -c "/bin/bash -login startx -- -depth 16"
    ;;
    *)
        echo "use start"
esac
