#!/bin/bash

if [ $# -eq 0 ]; then
    echo "usage: testiso <isofile> [id|ic|sd|sc|vd|vc]"
    echo
    echo "id    boot .iso as IDE disk"
    echo "ic    boot .iso as IDE cd-rom"
    echo "sd    boot .iso as SCSI disk"
    echo "sc    boot .iso as SCSI cd-rom"
    echo "vd    boot .iso as virtio disk"
    echo "vc    boot .iso as virtio cd-rom"
    exit 1
fi

case "${2}" in
  id) IF="ide"; MEDIA="disk";;
  ic) IF="ide"; MEDIA="cdrom";;
  sd) IF="scsi"; MEDIA="disk";;
  sc) IF="scsi"; MEDIA="cdrom";;
  vd) IF="virtio"; MEDIA="disk";;
  vc) IF="virtio"; MEDIA="cdrom";;
   *) IF="scsi"; MEDIA="cdrom";;
esac

echo qemu -m 256 -drive file=${1},if=${IF},media=${MEDIA},boot=on
qemu -m 256 -drive file=${1},if=${IF},media=${MEDIA},boot=on
