#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later

build() {
    map add_checked_modules '/drivers/char/agp/' '/drivers/gpu/drm/'
}

help() {
    cat <<HELPEOF
Adds KMS drivers to the initramfs image. To minimize the modules in the image,
add the autodetect hook too.
HELPEOF
}
