#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later

build() {
    add_runscript

    add_binary curl

    add_file "$(readlink -f /etc/ssl/certs/ca-certificates.crt)" /etc/ssl/certs/ca-certificates.crt
}

help() {
cat<<HELPEOF
  This hook loads the necessary modules for boot via PXE and HTTP.
HELPEOF
}
