#!/bin/bash

build() {
    add_module "nbd"

    add_runscript

    add_binary nbd-client
}

help() {
cat<<HELPEOF
  This hook loads the necessary modules for boot via PXE and NBD.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
