package src

type Config struct{
	Arch string
	OSName string
	IsoName string
	IsoLabel string
	IsoPublisher string
	IsoApplication string
	IsoVersion string
	InstallDir string
	WorkDir string
	OutDir string
	GpgKey string
	BootSplash bool
	ThemeName string
	ChannelName string
	TarBall bool
	TarComp string
	TarCompOpt string
	SfsComp string
	SfsCompOpt string
	IncludeInfo bool
	CustomizedSysLinux bool
	NorescureEntry bool
	AurHelperCommand string
	AurHelperPackage string
	AurHelperDepends []string
	AurHelperArgs []string
	Kernel string
	UserName string
	Password string
	UserShell string
	Memtest86 bool
	CowSpace string
	LocaleName string
	Cleaning bool
	NoConfirm bool
	NoColor bool
	//Nodepend bool
	NoChName bool
	NoCheckVersion bool
	NoEfi bool
	NoISO bool
	NoAur bool
	NoPkgBuild bool
	NoSigCheck bool
	NoRmWork bool
	Debug bool
	PacmanDebug bool
	GitVersion bool
}
