# I used https://github.com/soracqt/myarch as a reference.
# Thanks to soracqt(https://github.com/soracqt).

name: Build Alter Image

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      volumes:
        - /home/runner/work/alterdir/alterdir:/tmp/alterdir
      options: "--privileged"

    steps:
      - uses: actions/checkout@v2

      - name: Modify mirrorlist
        run: |
          env
          echo 'Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist

      - name: Sync reflector
        run: |
          pacman -Sy --noconfirm reflector

      - name: Run Reflecrtor
        run: |
          reflector --protocol https -c Japan --sort rate --save /etc/pacman.d/mirrorlist
      
      - name: Install Required Packages
        run: |
          pacman -Syyu --noconfirm git sudo python3 base-devel cmake ninja qt5-base archiso arch-install-scripts pyalpm

      - name: Populate keyrings
        run: |
          pacman-key --init
          ./tools/keyring.sh -a
        
      - name: Build AlterLinux
        run: ./build.sh -c zstd --noloopmod --noconfirm --cleanup $GITHUB_REF_NAME

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: alter_x86_64_$GITHUB_REF_NAME
          path: out

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - uses: actions/checkout@v2

      - name: Set title
        id: title
        run: echo "::set-output name=title::Alter Linux $GITHUB_RUN_NUMBER"

      - name: Set body
        id: body
        run: echo "::set-output name=body::これはautobuild.ymlによって自動生成されたイメージです。"

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: alter_x86_64_$GITHUB_REF_NAME

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.title.outputs.title }}
          name: ${{ steps.title.outputs.title }}
          body: ${{steps.body.outputs.body }}
          draft: false
          prerelease: false
          files: |
           alterlinux-$GITHUB_REF_NAME-*-x86_64.iso


