#!/bin/bash

build() {
    add_module "nls_iso8859-1"
    add_runscript
}

help() {
cat<<HELPEOF
  This hook loads the necessary modules for boot via loop device.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
